# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale:            "en-US"
title:             "Jennifer Haliewicz / HLT Portfolio"
name:              &name "Jennifer Haliewicz"
description:       &description "Portfolio for the University of Arizona HLT program"
url:               "https://www.jenniferhaliewicz.com"
remote_theme:      mmistakes/minimal-mistakes
baseurl:           
repository:        "rofljen/HLTProfessionalsite"
teaser:
breadcrumbs:       false
words_per_minute:  160
future:            true
read_more:         "disabled"
talkmap_link:      false

sidebar:
  nav: "main"
  author_profile: true
  
comments:
  provider:
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid:
    num_posts:
    colorscheme:

staticman:
  allowedFields:    ['name', 'email', 'url', 'message']
  branch:           "gh-pages"
  commitMessage:    "New comment."
  filename:         comment-{@timestamp}
  format:           "yml"
  moderation:       true
  path:             "_data/comments/{options.slug}"
  requiredFields:   ['name', 'email', 'message']
  transforms:
    email:          "md5"
  generatedFields:
    date:
      type:         "date"
      options:
        format:     "iso8601"

atom_feed:
  path:

# Navigation (Minimal Mistakes will render these in the header)
navigation:
  - title: "Home"
    url:   /
  - title: "Portfolio"
    url:   /portfolio/
  - title: "CV"
    url:   /cv/
  - title: "Blog"
    url:   /blog/

# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing
twitter:
  username:        &twitter
facebook:
  username:
  app_id:
  publisher:
og_image:

social:
  type:
  name:
  links:

# Analytics
analytics:
  provider:        "google-universal"
  google:
    tracking_id:

# Site Author
author:
  name: Jennifer Haliewicz
  avatar: /images/Jen2.jpg
  bio: |
    I use language data and open tools to<br> improve access, equity, and<br> performance in NLP systems.
  location: Portland, Oregon
  github: rofljen
  linkedin: jennifer-haliewicz

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding:          "utf-8"
markdown_ext:      "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:          kramdown
highlighter:       rouge
lsi:               false
excerpt_separator: "\n\n"
incremental:       false

# Markdown Processing
kramdown:
  input:           GFM
  hard_wrap:       false
  auto_ids:        true
  footnote_nr:     1
  entity_output:   as_char
  toc_levels:      1..6
  smart_quotes:    lsquo,rsquo,ldquo,rdquo
  enable_coderay:  false

# Collections
collections:
  teaching:
    output:       true
    permalink:    /:collection/:path/
  publications:
    output:       true
    permalink:    /:collection/:path/
  portfolio:
    output:       true
    permalink:    /:collection/:path/
  talks:
    output:       true
    permalink:    /:collection/:path/

# Defaults
defaults:
  - scope:
      path:   ""
      type:   posts
    values:
      layout:          single
      author_profile:  true
      read_time:       true
      comments:        true
      share:           true
      related:         true
  - scope:
      path:   ""
      type:   pages
    values:
      layout:         single
      author_profile: true
  - scope:
      path:   ""
      type:   teaching
    values:
      layout:         single
      author_profile: true
      share:          true
      comments:       true
  - scope:
      path:   ""
      type:   publications
    values:
      layout:         single
      author_profile: true
      share:          true
      comments:       true
  - scope:
      path:   ""
      type:   portfolio
    values:
      layout:         single
      author_profile: true
      share:          true
      comment:        true
  - scope:
      path:   ""
      type:   talks
    values:
      layout:         talk
      author_profile: true
      share:          true

# Sass/SCSS
sass:
  sass_dir:        _sass
  style:           compressed

# Outputting
permalink:         /:categories/:title/
timezone:          America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type:            liquid
  path:            /categories/
tag_archive:
  type:            liquid
  path:            /tags/

# HTML Compression
compress_html:
  clippings:       all
  ignore:
    envs:
      - development
